# yamllint disable rule:line-length
# SealedSecret voor Gitea registry-pull, cluster-breed inzetbaar.
# Gegenereerd met kubeseal --scope cluster-wide tegen de cluster-key; bevat geen plaintext.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgAXKH+Y20OUkQGZ1sFfx+kQEkirPMsTtrH/yJ+ku7n2zN5QKJOB0tjK/ClEiGMCNXthP8ZO5GIf6qEegX1akpPSKK7HR+CfDBBu2EbXfa+InJ7Hd2UhP5koOjv9t8DmI0L0v/JndoeosfjeBOP9VJEj49ZiX3GK+SbdMNZ4+ApURqnkHGA2fzTFmHQLtHHfQrOH5NKeY2jM/5UrJ6tJPp/4+qPkLwO6oDzwWGCQgLYOmDGXvANpYz+UmT8iv7HzLMBdOOfTGU1L61dwhcqcMwi+nRy0rHf1G+nNqQizsc5JJNGZco11c2vb93gCsVAZyi+n+c06ugRa8cbK9wjgP/MzMffF5WI682EiwJnROq0aOkD7LSqNa9DJJfIEswO3s68SdG8YL1cjjGAbTzF2NryQej5P8/0zKV4twLNpyCc1Gc10aswUOqdUkY/bHcb1+QJic35f43FcamhiDnX9Wp2rBADdwkWeLjScBP//HXsSQ6lbed7AdoRQULgdECE1a+DSnf86xUd9tWjVDKinTxYMwxTIiIhPq1cWpgHzuvWeeT9roZCs8tmC4dTlQv/CMUYCSuPJJIKzJiBENnnnMdaK1SrbD1PjcMSHP2b03ZhHj9To+ZQOcvAYkpcmTzzOFVjN7wlMapMIAVjCywCUKqIpTS+WUQxKG0FgZqxx41QE+1DCqkRAo0r9+RZ5lNMOlZalZ2uLwcvS3sEI5Ka5wGwLB7y0ozk3KvyHbQyouJuqHa2WWRjASOGyB64Md2JgBS/9Scz7fj7iipSu7OjQN8Zsy3Eedh4o598PaXMDvk0HYu8uXRVHqQsuqe5Z/rRrKbAWewLjcDI7DprFWOpYggDG+S9m3H+RGRaPxNYknIAt7Ddz4FrXX4cIeUXDcsTtqCywAiEIDnkdd2jhKjMkKBUo3+ONltLhzHb8mtJPeUquzT2DUZL6zylple/hw9URH0oPfJwpBqXBlW36ExL3BG9Pe4IEhPbDVlv7N8B+F+6BF1pXumJKoMONNzM4IMUJnVZtefDHUlsvFY+ZtabDA1tKF1HoLdg+XUO1aI9yNij1vQI9YeC7J2NjC6SWMHpkZUCwZmRwk8qTxmOypSPB45S0DIiFkBUJlq+EnArQMCzIQe8ds+oT4SnPURIppazX8eecn4cX5cdUZdDQeSbdOkumY2FE/xb2a9zcuMdbZsoOi5FeOmMLOICpLHW6C4E=
  template:
    metadata:
      name: gitea-registry
    type: kubernetes.io/dockerconfigjson
