# yamllint disable rule:line-length
# SealedSecret voor Gitea registry-pull, cluster-breed inzetbaar.
# Gegenereerd met kubeseal --scope cluster-wide tegen de cluster-key; bevat geen plaintext.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgDVadCpxldIH5LsdsyrlzNICV8eX9vfLtW7DZJx88rXHFSb7DdWl10jeggsqXvZrSktYQsvhk4/VIZv+dG7Ve1XaRcIBIj2TxcsckfSxzDX9xgA+Cpeks8vvk/JY0py98ti90cRIstBsHSxFOdbKzPZs8ne8FUv489HPcefw3Db0UhQ2Ov0rWCheF2zBZ9/u6tRBSCzQNIAWIdnhMXTefPYRDyJ3kz/uGtQImyDDrygmSMXFrywp52dlsKGqKzbatkHvTaG6hBtctNdXFyPi3SwFx91mV1tjZapCg9TXeK7zZuW45RvjB9s/0UdaUloLfQ1j6y5yP1CelinXGAgJ4clwnCjX6ILq83PpQ9f5bryCKgh5BVM364aGZJdQw9a5doQyD01IHiCp56WnfqcmWTp4xJDLQTHaJ6k9j5wS7TBiGdv7tjHjC8n3p7sgBuEZUMd8xGxlmqW19rglzKhficNypKDWvCv6wmhU9x+7ckd1L38RPNoqOSP851GLaSXz9MSw/pvZL974tb/r6/V0BiX7IsZ8To1/JaXW3tz4imyCEAaWWj3MsCcPbi+cOLOqvz8bnl7+505pWNrFShFvH6cPOyICEItqGxG8UYo5tVpiggd2AYT7YikiQmokWxFscGkweuuDVKC8EGjOXdjo+PkOkUkSgVjTVA1U3YinDU6wzW8xHtuujvTImlzRgvSJzf74p+0H3S7hcFSLDz0NaWI13DzG4vl5hQfNfvLFjKhVcYyEBW0iDD0o84SrIxesrgZ5Nm8p/0Gaz3SqBByfvw4MGmMZ68OtE/SGCipCuwBIY2akU+plYGH2akLytVSo7S0rMwJ/zYXZX7POwFY2TmQUU1Xtg6NymSz/SlOJKHmRUTKlsnBYDyTEEHUPy+dHKoVDGg64JLRb5oZresxhZNDy144LKPD1pPP9K0N6uotVZdcaf6DCUXOrsRNbkkZyhiQdjSn
  template:
    metadata:
      name: gitea-registry
    type: kubernetes.io/dockerconfigjson
