# yamllint disable rule:line-length
# SealedSecret voor Gitea registry-pull (namespace-scoped: default).
# Gegenereerd met kubeseal tegen de cluster-key; bevat geen plaintext.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgDB8h5V+jhh4tJYsujGZLaud8kCya3aSBDaQyR5L2qU94YD3QVvfyeFGJzLh/OO08yOu1G+UFg55hy3QmMLOL+T9D2UFzWD5y6Tol/0tPhTt4xmxBIoUA94ryUIWbahWmETci8BkC5jpMhF3jlsALQs/pUv341LbfbE4jUTk8sxoub2+qFabgbvRxF13vkTgBArIv0S/v9Z6OueiJkiz1VgQqV4Hikz29zNVk6U9/35Dzek9zWgj9Bij1Fq949VXTZf9Sa2aUL/kWonP/DSLYQRmvYYIs9N1u9/MDQY0KjxZQcQKRPgjrGHiaB2bKH7mGhsedHpDVWlXxFmb0yNB4DFZ99gUwMe6PwdrYDugib3ORZ+Y0C2Lws/rEPQr0IXXbbvFb0d4Ei0ck52pdhUkublwYeZ+ukcME1rBH3IYG54IDkaJTXUgtjJpoff1wTSAtu8lBMLDJ5w7ZO/o1ThsOi4llTKRVb09+4deI8dngn9IGzLhz29yDmdb2sZ2eVtyO4BNBeS7Zc1sKEewsLvWdh+Xz/3zdn+FjNcz8Rn20yrWMOfz0Won6lv+wN41yzycFloMDzOaNAFLRCE54HT9+16pN0PpBmcQGgN72ZFnq7+9yBZYDIHGtTGbCp9X5DdzmU/twfed9JSEa+grbE3HquGGd09dIRXVVpDKmNeA5/MoKRY0he49Wsrso4Ux8mjfDCs2XTrePETexx0u8d+3Okq41lO+cA18eFgFztlXt/8CzKtPym7DAfTJRSdHiPZ2TR3G8W2+oDhFdigXz03HZEPOnapaPf/sB9ftP5DCQMeDGJMczVTcY7VJZSMFJPOjf9ZSZu22UViaL7f9zcutTOm0hWXZzJtgSeUahSsF/lrGv01atz8y+kGbCeEYS6U5tz63w4A+bqZ91RgS8TpCFFW76YnbuPPzIFEgRbKm0AZpUdBfUYse9OsD/AMHXM=
  template:
    metadata:
      name: gitea-registry
      namespace: default
    type: kubernetes.io/dockerconfigjson
