# yamllint disable rule:line-length
# SealedSecret voor Gitea registry-pull, cluster-breed inzetbaar.
# Gegenereerd met kubeseal --scope cluster-wide tegen de cluster-key; bevat geen plaintext.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgB4LMWuBXksgYsqftDe5gDc+ZWJylDBtFN/+sDVBQmmexJ2l7q4+MSG/xpDACGsPfET2Kf53rupHXJt/e6rhpzACdiJycCJ1ymTp6Uu3m2k+KtdSOy4OtISGEdw5oNSeC58xWw86wVTxV+Ju+ARHGANVxdQhoM5XfT0hiYQdnIlfS0BJJPl78UQzPibCeiNv8xvhCyukPjFgi7oBcG9njxqLSU3932g6mBs8HQ59rb9R0XEXvpaeIJhZ7b7GOsdRmVco7nGwRB6nUr+gd9tvru3WSwz+sYzUpdfrHsvZiX/HFwCgLTiam8MXKK+K4mA6dGNgxNL90Bl5pE01WulGAT6ZwfvtdZ3aZTtPgtOAyRthcO+/Fq8GxizKoXjkRl5DCTJxhKsmL14GRcsc6VNNDJJFcuB7dSor3c9Gb4Kxu+KltPWLHv9rq5+VjzrLjB9EAZac2sfSZiTcoRrLw6pfuXY8fOyXItwJXOzn77pdx4970UEjCBcS8ywIfOgzHUIkdN7G1z6Buprq95mSBUAa8vOT12XV/Pp6defCvEJtlnSWTHvA1s/352dkMmk5z5jBThx0nkzkvCNeX9tP1p0aWAhTk1gL+enRn+btwYD/sNhCw2RX2Egmfzl/2IOUigPwCrueVmD3x2+MR4LoUJP1i5IJ8oqcHfsArGCH1CwOis1bXmiIBVjn+zdhJEL+8vWGV/We+0nNVi645itZAYfpgO8Rh2jWtGMr0V0nJHwVr16I0QofnTv0Q+oVmUX72V923tUcH2fp0Y7FPMtCBkl1Uecxp5lu/C/t1q9Tg2nvdhgUfAhXgNeG3WNfIa9q07zUvrcDnTiGg9M68Wncnx8TwcbvqwQ7ZxziaUk6FQ9AXcBtchHfdDg/HPaKemD2fg2IzsVYl4nRHo+lOa05u/RG+Wohg38SZGI3Cdh24KQkDYY8mmkDUj0vaFVkOZqnLo=
  template:
    metadata:
      name: gitea-registry
    type: kubernetes.io/dockerconfigjson
