name: CD Worker

on:
  push:
    branches: [main]
    paths:
      - 'src/Worker/**'
      - 'tests/Worker.Tests/**'
      - 'global.json'
      - 'version.json'
      - '.github/workflows/cd-worker.yml'
      - '.github/workflows/cd-template.yml'

permissions: {}

jobs:
  cd:
    uses: ./.github/workflows/cd-template.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      project-path: src/Worker/Worker.csproj
      image-name: beheerder/learncicd-worker
      values-file: charts/learncicd-worker/values-devtest.yaml
      tag-branch: ci/image-tag-update-worker
    secrets: inherit
