name: CD

on:
  push:
    branches: [main]
    paths-ignore:
      - 'charts/**'
      - 'argocd/**'
      - 'docs/**'
      - '**/*.md'
      - '.gitignore'
      - 'LICENSE'

permissions: {}

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cd:
    name: CD
    uses: ./.github/workflows/cd-template.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      project-path: src/Api/Api.csproj
      image-name: beheerder/learncicd
      values-file: charts/learncicd/values-devtest.yaml
      tag-branch: ci/image-tag-update
    secrets: inherit
